# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b91e6d754ed75218cb1d1c9f034167c8f0bd7648c0045d0c88d02c7a4d43829e43d3d18b4950d0363752c561500bd49405618bd8aa4e638f081ba0bb1cc5300d

test:
  secret_key_base: 5cb6de96baf78b6c4f9d79140249d15c05bc06ecbd138af0030543821b96b210b350b547c3b4c5c9c7e651640cad8c120dbd21fa8fda1c9cf4b7ff658a0f880b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
